### PR TITLE
Automatically add # to hex color if users do not include it

### LINKED ISSUE #987: Color selector does not work for user input without a '#'
### Description

Currently, if the user types in a custom hex color code without a '#' character at the start of the string, the saved color would not work.

### Requirements

- this is fixed so that a user input without a '#' would have it automatically inserted

### PR DESCRIPTION
**Pull request by KailashSiva**
### Description 🧾

This PR will resolve #987 - color selector did not work when user does not add # to hex color. This pr prepends # if it is not already in the text field color. Note that it still allows users to completely clear the text field. 

The code is a tiny bit janky - whenever the text field changes, before changing color using setColor, it checks if the color starts with #. If it doesn't, then # is added. If the text field is simply "" then # is not added.

Happy to implement without automatically prepending # to the text field. 

### Testing

Enter a hex color without starting with #. 

### Checklist

- [x] 📍 You have assigned yourself to this pull request.
- [x] 🔗 You have linked an issue to which this pull request closes.
- [x] 💭 Leave any relevant specific directions to reviewers.
- [x] 👀 No secrets in clear text in the pull request.
- [x] 🎟️ To categorise release notes, the pull request should be labelled with at least one of these labels:
  - `feature`: for application feature improvement or new features
  - `bug`: fixing something that previously wasn't working
  - `dev`: development-side related changes
  - `docker`: updates to the Docker code
  - `setup`: changes to the setup/infrastructure of the codebase
  - `test`: updates to internal testing

### CODE REVIEW

File: client/src/components/controls/ColorPicker.tsx [hunk 1]
```diff
@@ -84,7 +84,13 @@ const ColorPicker: React.FC<ColorPickerProps> = ({
             label="Hex"
             variant="outlined"
             value={textFieldValue}
-            onChange={(e) => setColor(e.target.value)}
+            onChange={(e) => {
+              let newColor = e.target.value
```
Comment (mark-trann) [inline client/src/components/controls/ColorPicker.tsx]: nitpick: change it to a const

```suggestion
              const newColor = e.target.value
```

**Review by mark-trann — APPROVED** [review]
lgtm! would be helpful add a screenshot of a test result :)

**Comment by mark-trann** [comment]
(tested already, disregard earlier comment about including testing screenshot)

**Comment by mark-trann** [comment]
o wait i mustve been sleepy asf reviewing this - mb will revert the const change 💀
