### PR TITLE
958 fix keyboard shortcut undo

### LINKED ISSUE #958: Keyboard shortcuts for undo and redo fall behind undo & redo buttons
### Description

There is a bug where if you make changes and undo such changes, the keyboard shortcut of the undo will undo much more than the undo button on the app.

### Requirements
- Fix implementation such that the keyboard shortcut is consistent with the buttons.

### PR DESCRIPTION
**Pull request by KailashSiva**
### Description 🧾

Closes #958 . This PR will ensure the ctrl z keyboard shortcut only undoes one action - mirroring the behaviour of the undo button.

Multiple eventListeners were previously being added for ctrl z, triggering multiple undos for one ctrl z. 

### Testing

Adding courses and then spamming a combination of undo and redo with only the buttons, and then only with the shortcuts. The behaviour should be identical. 

Happy to make a screen recording showing changes. 

### Checklist

- [x] 📍 You have assigned yourself to this pull request.
- [x] 🔗 You have linked an issue to which this pull request closes.
- [x] 💭 Leave any relevant specific directions to reviewers.
- [x] 👀 No secrets in clear text in the pull request.
- [x] 🎟️ To categorise release notes, the pull request should be labelled with at least one of these labels:
  - `feature`: for application feature improvement or new features
  - `bug`: fixing something that previously wasn't working
  - `dev`: development-side related changes
  - `docker`: updates to the Docker code
  - `setup`: changes to the setup/infrastructure of the codebase
  - `test`: updates to internal testing

### CODE REVIEW

File: client/src/components/controls/History.tsx [hunk 1]
```diff
@@ -262,12 +263,16 @@ const History: React.FC = () => {
...
 
   useEffect(() => {
-    window.addEventListener('keydown', handleKeyDown);
-    window.addEventListener('mouseup', () => setIsDrag(false)); // Only triggers useEffect function if isDrag was true previously
-  }, [disableLeft, disableRight]);
+    document.addEventListener('keydown', handleKeyDown);
+    document.addEventListener('mouseup', () => setIsDrag(false)); // Only triggers useEffect function if isDrag was true previously
+
+    return () => {
+      document.removeEventListener('keydown', handleKeyDown);
```
Comment (mark-trann) [inline client/src/components/controls/History.tsx:289]: not directly relevant to task but we should also remove the other event listener here too

File: client/src/components/controls/History.tsx [hunk 2]
```diff
@@ -221,18 +221,19 @@ const History: React.FC = () => {
...
     if (!term) return;
 
+
     const currentTimetable = displayTimetables[term][selectedTimetable];
 
     event.preventDefault();
-
     if (!isMacOS && event.ctrlKey) {
-      if (event.key === 'z' && !disableLeft && actionsPointer.current[currentTimetable.id] > 1) {
+      if (event.key === 'z' && !disableLeft) {
```
Comment (mark-trann) [inline client/src/components/controls/History.tsx]: question: what happened to the actionsPointer condition to check the hashmap?

Comment (mark-trann) [reply client/src/components/controls/History.tsx]: Seems like it was used to prevent the undo of the user's class slots being loaded into the timetable. A bit silly given that the "Undo" button does that as well already...

**Review by mark-trann — APPROVED** [review]
